Vagoo/Vagoo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('entities/', include('entities.urls')),
    path('accounts/', include('accounts.urls'))
]

if settings.DEBUG:
    from django.conf.urls.static import static

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Vagoo/accounts/urls.py
from django.urls import path
from .views import Login, ProfileDetails, CreateProfile
from django.contrib.auth.views import LogoutView

app_name = 'accounts'

urlpatterns = [
    path('login/', Login.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/details/', ProfileDetails.as_view(), name='profile_details'),
    path('profile/edit/', CreateProfile.as_view(), name='profile_create'),
]

Vagoo/entities/urls.py
from django.urls import path
from .views import MovieCreate, MovieShowDetails, MovieShowList, BookCreate, BookShowList, BookShowDetails,\
    TheaterCreate, TheaterShowList, TheaterShowDetails, SongCreate, SongShowList, SongShowDetails, JourneyCreate,\
    JourneyShowList, JourneyShowDetails


app_name = 'entities'

urlpatterns = [
    path('movies/create/', MovieCreate.as_view(), name='movies_create'),
    path('movies/<int:pk>/', MovieShowDetails.as_view(), name='movies_details'),
    path('movies/list/', MovieShowList.as_view(), name='movies_list'),
    path('books/create/', BookCreate.as_view(), name='books_create'),
    path('books/list/', BookShowList.as_view(), name='books_list'),
    path('books/<int:pk>/', BookShowDetails.as_view(), name='books_details'),
    path('theaters/create/', TheaterCreate.as_view(), name='theaters_create'),
    path('theaters/list/', TheaterShowList.as_view(), name='theaters_list'),
    path('theaters/<int:pk>/', TheaterShowDetails.as_view(), name='theaters_details'),
    path('songs/create/', SongCreate.as_view(), name='songs_create'),
    path('songs/list/', SongShowList.as_view(), name='songs_list'),
    path('songs/<int:pk>/', SongShowDetails.as_view(), name='songs_details'),
    path('journeys/create/', JourneyCreate.as_view(), name='journeys_create'),
    path('journeys/list/', JourneyShowList.as_view(), name='journeys_list'),
    path('journeys/<int:pk>/', JourneyShowDetails.as_view(), name='journeys_details'),
]

Vagoo/entities/models.py
from django.db import models
import datetime
# from django.contrib.gis.db import models
from location_field.models.plain import PlainLocationField
from languages.fields import LanguageField
from django.urls import reverse
import pycountry


# Future options:
# * Add User who add an entity to database


def year_choices():
    return [(r, r) for r in range(1884, datetime.date.today().year + 1)]


def current_year():
    return datetime.date.today().year


# Create your models here.
class Movie(models.Model):
    class Meta:
        verbose_name = \
            'فیلم'
        verbose_name_plural = 'فیلم'

    name = models.CharField('نام فیلم', max_length=150)
    director = models.CharField('نام کارگردان', max_length=100)
    year_choices = year_choices()
    year = models.IntegerField('سال تولید', choices=year_choices, default=current_year)

    COMEDIC_GENRE = 1
    DRAMA_GENRE = 2
    MUSICAL_GENRE = 3
    THRILLER_GENRE = 4
    ACTION_GENRE = 5
    ROMANCE_GENRE = 6
    MELODRAMA_GENRE = 7
    MYSTERY_GENRE = 8
    SCI_FI_GENRE = 9
    FANTASY_GENRE = 10
    HORROR_GENRE = 11
    WESTERN = 12
    NOIR_GENRE = 13
    ADVENTURE_GENRE = 14
    OTHERS = 15

    genre_choices = [
        (COMEDIC_GENRE, 'کمدی'),
        (DRAMA_GENRE, 'درام'),
        (MUSICAL_GENRE, 'موزیکال'),
        (THRILLER_GENRE, 'تریلر'),
        (ACTION_GENRE, 'اکشن'),
        (ROMANCE_GENRE, 'رمانتیک'),
        (MELODRAMA_GENRE, 'ملودرام'),
        (MYSTERY_GENRE, 'معمایی'),
        (SCI_FI_GENRE, 'علمی-تخیلی'),
        (FANTASY_GENRE, 'فانتزی'),
        (HORROR_GENRE, 'ترسناک'),
        (WESTERN, 'وسترن'),
        (NOIR_GENRE, 'نوآر'),
        (ADVENTURE_GENRE, 'ماجراجویانه'),
        (OTHERS, 'سایر'),
    ]

    genre = models.IntegerField('سبک', choices=genre_choices)
    image = models.ImageField('پوستر فیلم', upload_to='entities/films', blank=True, null=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('entities:movies_details', args=[self.id])


class Book(models.Model):
    class Meta:
        verbose_name = \
            'کتاب'
        verbose_name_plural = 'کتاب'

    name = models.CharField('نام کتاب', max_length=150)
    author = models.CharField('نویسنده', max_length=150)
    publisher = models.CharField('انتشارات', max_length=100)
    isbn = models.CharField('شابک', max_length=13)

    LITERATURE = 1
    MYTHICAL = 2
    ECONOMY = 3
    ARCHEOLOGY = 4
    HISTORY = 5
    DAIRY = 6
    NOVEL = 7
    SHORT_STORY = 8
    MYSTICISM = 9
    RELIGION = 10
    PSYCHOLOGY = 11
    BIOGRAPHY = 12
    POLITICS = 13
    SOCIOLOGY = 14
    HUMANITIES = 15
    MEDICAL = 16
    PHILOSOPHY = 17
    CHILDREN_AND_TEENAGER = 18
    REPORTING = 19
    INTERVIEW = 20
    ARTICLE = 21
    MUSIC = 22
    ART = 23
    OTHERS = 24

    subject_choices = [
        (LITERATURE, 'ادبیات'),
        (MYTHICAL, 'اسطوره‌ای'),
        (ECONOMY, 'اقتصاد'),
        (ARCHEOLOGY, 'باستان‌شناسی'),
        (HISTORY, 'تاریخ'),
        (DAIRY, 'خاطره‌نویسی'),
        (NOVEL, 'رمان'),
        (SHORT_STORY, 'داستان کوتاه'),
        (MYSTICISM, 'عرفان'),
        (RELIGION, 'دین'),
        (PSYCHOLOGY, 'روان‌شناسی'),
        (SOCIOLOGY, 'جامعه‌شناسی'),
        (HUMANITIES, 'علوم‌انسانی'),
        (MEDICAL, 'پزشکی'),
        (PHILOSOPHY, 'فلسفه'),
        (CHILDREN_AND_TEENAGER, 'کودک و نوجوان'),
        (REPORTING, 'گزارش‌نویسی'),
        (INTERVIEW, 'مصاحبه'),
        (ARTICLE, 'مقاله'),
        (MUSIC, 'موسیقی'),
        (ART, 'هنر'),
        (OTHERS, 'سایر'),
    ]
    subject = models.IntegerField('موضوع', choices=subject_choices)
    image = models.ImageField('طرح روی جلد کتاب', upload_to='entities/books', blank=True, null=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('entities:books_details', args=[self.id])


class Song(models.Model):
    class Meta:
        verbose_name = 'ترانه'
        verbose_name_plural = 'ترانه'

    name = models.CharField('نام اثر', max_length=200)
    singer = models.CharField('خواننده', max_length=150)
    composer = models.CharField('آهنگساز', max_length=150)
    songwriter = models.CharField('ترانه‌سرا', max_length=150)
    image = models.ImageField('پوستر آلبوم یا ترانه', upload_to='entities/songs', blank=True, null=True)

    # language: add this field later

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('entities:songs_details', args=[self.id])


class Theater(models.Model):
    class Meta:
        verbose_name = 'تئاتر'
        verbose_name_plural = 'تئاتر'

    name = models.CharField('نام اثر', max_length=200)
    director = models.CharField('کارگردان', max_length=150)
    scriptwriter = models.CharField('نمایشنامه‌نویس', max_length=150)
    genre_choices = Movie.genre_choices
    genre = models.IntegerField('ژانر', choices=genre_choices)
    image = models.ImageField('پوستر تئاتر', upload_to='entities/theater', blank=True, null=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('entities:theaters_details', args=[self.id])


class JourneyImages(models.Model):
    class Meta:
        verbose_name = 'عکس سفر'
        verbose_name_plural = 'عکس سفر'

    image_name = models.CharField('نام عکس', max_length=100)
    image = models.ImageField(upload_to='upload_to_gallery')
    journey = models.ForeignKey('Journey', on_delete=models.CASCADE)
    default = models.BooleanField('تصویر پیش‌فرض', default=False)

    def __str__(self):
        return self.image_name

    def upload_to_gallery(self, filename):
        return f"entities/journeys/{self.journey.title}/filename"


class Journey(models.Model):
    class Meta:
        verbose_name = 'سفر'
        verbose_name_plural = 'سفر'

    title = models.CharField('عنوان', max_length=255)
    city = models.CharField('شهر', max_length=255)
    location = PlainLocationField(based_fields=['city'], zoom=7, verbose_name='موقعیت جغرافیایی', null=True, blank=True)
    country = models.CharField('کشور', max_length=100)
    province = models.CharField('استان/ایالت', max_length=100)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('entities:journeys_details', args=[self.id])

Vagoo/entities/views.py
from django.shortcuts import render
from django.views.generic import DetailView, CreateView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Movie, Book, Theater, Song, Journey
from .form import MovieCreateForm, BookCreateForm, TheaterCreateForm, SongCreateForm, JourneyCreateForm
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy, reverse


# Create your views here.

class MovieCreate(LoginRequiredMixin, CreateView):
    model = Movie
    template_name = 'entities/movie_create.html'
    form_class = MovieCreateForm
    login_url = 'accounts:login'


class MovieShowList(ListView):
    model = Movie
    template_name = 'entities/movie_list.html'
    context_object_name = 'movies'


class MovieShowDetails(DetailView):
    model = Movie
    template_name = 'entities/movie_details.html'
    context_object_name = 'movie_details'


class BookCreate(LoginRequiredMixin, CreateView):
    model = Book
    template_name = 'entities/book_create.html'
    form_class = BookCreateForm
    login_url = 'accounts:login'


class BookShowList(ListView):
    model = Book
    template_name = 'entities/book_list.html'
    context_object_name = 'books'


class BookShowDetails(DetailView):
    model = Book
    template_name = 'entities/book_details.html'
    context_object_name = 'book_details'


class TheaterCreate(LoginRequiredMixin, CreateView):
    model = Theater
    template_name = 'entities/theater_create.html'
    form_class = TheaterCreateForm
    login_url = 'accounts:login'


class TheaterShowList(ListView):
    model = Theater
    template_name = 'entities/theater_list.html'
    context_object_name = 'theaters'


class TheaterShowDetails(DetailView):
    model = Theater
    template_name = 'entities/theater_details.html'
    context_object_name = 'theater_details'


class SongCreate(LoginRequiredMixin, CreateView):
    model = Song
    template_name = 'entities/song_create.html'
    form_class = SongCreateForm
    login_url = 'accounts:login'


class SongShowList(ListView):
    model = Song
    template_name = 'entities/song_list'
    context_object_name = 'songs'


class SongShowDetails(DetailView):
    model = Song
    template_name = 'entities/song_details.html'
    context_object_name = 'song_details'


class JourneyCreate(LoginRequiredMixin, CreateView):
    model = Journey
    template_name = 'entities/journey_create.html'
    form_class = JourneyCreateForm


class JourneyShowList(ListView):
    model = Journey
    template_name = 'entities/journey_list.html'
    context_object_name = 'journeys'


class JourneyShowDetails(DetailView):
    model = Journey
    template_name = 'entities/journey_details.html'
    context_object_name = 'journey_details'

Vagoo/entities/templates/entities/book_create.html
<html>
    <head>
        <meta charset="UTF-8">
        <title>Book Create Form</title>
    </head>
    <body>
        {% if request.user.is_authenticated %}
            <a href="{% url "accounts:logout" %}" >خروج کاربر</a>
        {% else %}
            <a href="{% url "accounts:login" %}"}>ورود به حساب کاربری</a>
        {% endif %}
        <form action="." method="POST">
            {% csrf_token %}
            {{ form.as_p }}

            <button type="submit">اضافه کردن کتاب جدید</button>
        </form>
    </body>
</html>

Vagoo/entities/templates/entities/book_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Details of {{ book_details.name }}</title>
</head>
<body>
    {% if request.user.is_authenticated %}
        <a href="{% url "accounts:logout" %}">خروج کاربر</a>
    {% else %}
        <a href="{% url "accounts:login" %}" }
    {% endif %}
    <ul>
        <li> {{ book_details.name }} </li>
        <li> {{ book_details.author }} </li>
        <li> {{ book_details.publisher }} </li>
        <li> {{ book_details.isbn }} </li>
        <li> {{ book_details.get_subject_display }} </li>
    </ul>

</body>
</html>

Vagoo/entities/templates/entities/book_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Books List</title>
</head>
<body>
    {% if request.user.is_authenticated %}
        <a href="{% url "accounts:logout" %}">خروج کاربر</a>
    {% else %}
        <a href="{% url "accounts:login" %}" }>ورود کاربر</a>
    {% endif %}
    {% if books %}
        <ul>
            {% for book in books %}
                <li>
                    <a href="{% url "entities:books_details" pk=book.id%}">
                    {{ book.name }}
                    </a>
                </li>
            {% endfor %}
        </ul>
    {% endif %}
    <a href="{% url "entities:books_create" %}" target="_blank"> اضافه کردن کتاب جدید </a>

</body>
</html>

Vagoo/entities/templates/entities/journey_create.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Journey Create Form</title>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


        <link href="https://static.neshan.org/sdk/leaflet/1.4.0/leaflet.css" rel="stylesheet" type="text/css">
        <script src="https://static.neshan.org/sdk/leaflet/1.4.0/leaflet.js" type="text/javascript"></script>


    </head>
    <body>
    {% if request.user.is_authenticated %}
        <a href="{% url "accounts:logout" %}">خروج کاربر</a>
    {% else %}
        <a href="{% url "accounts:login" %}" }>ورود کاربر</a>
    {% endif %}


        <h1>Map has not completed yet</h1>
        <form action="." method="POST">
            {% csrf_token %}
            {% include "entities/_form_field.html" with field=form.title %}
            {% include "entities/_form_field.html" with field=form.city %}
            {% include "entities/_form_field.html" with field=form.province %}
            {% include "entities/_form_field.html" with field=form.country %}
            {% include "entities/_form_field.html" with field=form.location %}
            <div id="map" style="width: 600px; height: 450px; background: #eee; border: 2px solid #aaa;"></div>
            <button type="submit">اضافه کردن سفر جدید</button>
        </form>

        <script type="text/javascript">
                var myMap = new L.Map('map', {
                    key: 'service.PdrGzfoRNFPnWcUoLhcevDXR0ubM34XQcFwCcoiV',
                    maptype: 'dreamy',
                    poi: true,
                    traffic: false,
                    center: [35.699739, 51.338097],
                    zoom: 14
                });
                myMap.setMapType("neshan");
        </script>
    </body>
</html>

Vagoo/entities/templates/entities/journey_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Details of {{ journey_details.name }}</title>
</head>
<body>
    {% if request.user.is_authenticated %}
        <a href="{% url "accounts:logout" %}">خروج کاربر</a>
    {% else %}
        <a href="{% url "accounts:login" %}" }>ورود کاربر</a>
    {% endif %}
    <ul>
        <li> {{ journey_details.title }} </li>
        <li> {{ journey_details.city }} </li>
        <li> {{ journey_details.location }} </li>
        <li> {{ journey_details.country }} </li>
        <li> {{ journey_details.province }} </li>
    </ul>

</body>
</html>

Vagoo/entities/templates/entities/journey_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Journey List</title>
</head>
<body>
    {% if request.user.is_authenticated %}
        <a href="{% url "accounts:logout" %}">خروج کاربر</a>
    {% else %}
        <a href="{% url "accounts:login" %}" }>ورود کاربر</a>
    {% endif %}
    {% if journeys %}
        <ul>
            {% for journey in journeys %}
                <li>
                    <a href="{% url "entities:journeys_details" pk=journey.id%}">
                    {{ journey.title }}
                    </a>
                </li>
            {% endfor %}
        </ul>
    {% endif %}
    <a href="{% url "entities:journeys_create" %}" target="_blank"> اضافه کردن سفر جدید </a>

</body>
</html>

Vagoo/entities/templates/entities/movie-create.html
<html>
    <head>
        <meta charset="UTF-8">
        <title>Movie Create Form</title>
    </head>
    <body>
        <form action="." method="POST">
            {% csrf_token %}
            {{ form.as_p }}

            <button type="submit">اضافه کردن فیلم جدید</button>
        </form>
    </body>
</html>

Vagoo/entities/templates/entities/movie_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Details of {{ movie_details.name }}</title>
</head>
<body>
    {% if request.user.is_authenticated %}
        <a href="{% url "accounts:logout" %}">خروج کاربر</a>
    {% else %}
        <a href="{% url "accounts:login" %}" }>ورود کاربر</a>
    {% endif %}
    <ul>
        <li> {{ movie_details.name }} </li>
        <li> {{ movie_details.director }} </li>
        <li> {{ movie_details.year }} </li>
        <li> {{ movie_details.get_genre_display }} </li>
    </ul>

</body>
</html>

Vagoo/entities/templates/entities/movie_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Movies List</title>
</head>
<body>
    {% if request.user.is_authenticated %}
        <a href="{% url "accounts:logout" %}">خروج کاربر</a>
    {% else %}
        <a href="{% url "accounts:login" %}" }>ورود کاربر</a>
    {% endif %}
    {% if movies %}
        <ul>
            {% for movie in movies %}
                <li>
                    <a href="{% url "entities:movies_details" pk=movie.id %}">
                    {{ movie.name }}
                    </a>
                </li>
            {% endfor %}
        </ul>
    {% endif %}
    <a href="{% url "entities:movies_create" %}" target="_blank"> اضافه کردن فیلم جدید </a>

</body>
</html>

Vagoo/entities/templates/entities/song_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add Song</title>
</head>
<body>
    {% if request.user.is_authenticated %}
        <a href="{% url "accounts:logout" %}">خروج کاربر</a>
    {% else %}
        <a href="{% url "accounts:login" %}" }>ورود کاربر</a>
    {% endif %}
        <h1>Add An Attractive Song You Have Seen! </h1>
        <form action="." method="POST">
            {% csrf_token %}
            {{ form.as_p }}

            <button type="submit">اضافه کردن ترانه جدید</button>
        </form>
</body>
</html>

Vagoo/entities/templates/entities/song_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Details of {{ book_details.name }}</title>
</head>
<body>
    {% if request.user.is_authenticated %}
        <a href="{% url "accounts:logout" %}">خروج کاربر</a>
    {% else %}
        <a href="{% url "accounts:login" %}" }>ورود کاربر</a>
    {% endif %}
    <ul>
        <li> {{ song_details.name }} </li>
        <li> {{ song_details.singer }} </li>
        <li> {{ song_details.composer }} </li>
        <li> {{ song_details.songwriter }} </li>
    </ul>

</body>
</html>

Vagoo/entities/templates/entities/song_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Songs list</title>
</head>
<body>
    {% if request.user.is_authenticated %}
        <a href="{% url "accounts:logout" %}">خروج کاربر</a>
    {% else %}
        <a href="{% url "accounts:login" %}" }>ورود کاربر</a>
    {% endif %}
    {% if songs %}
    <ul>
        {% for song in songs %}
            <li>
                <a href="{% url "entities:songs_details" pk=song.id %}">
                {{ song.name }}
                </a>
            </li>
        {% endfor %}
    </ul>
    {% endif %}
    <a href="{% url "entities:songs_create" %}" target="_blank"> اضافه کردن موسیقی جدید </a>
</body>
</html>

Vagoo/entities/templates/entities/theater_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Details of {{ book_details.name }}</title>
</head>
<body>
    {% if request.user.is_authenticated %}
        <a href="{% url "accounts:logout" %}">خروج کاربر</a>
    {% else %}
        <a href="{% url "accounts:login" %}" }>ورود کاربر</a>
    {% endif %}
    <ul>
        <li> {{ theater_details.name }} </li>
        <li> {{ theater_details.director }} </li>
        <li> {{ theater_details.scriptwriter }} </li>
        <li> {{ theater_details.get_genre_display }} </li>
    </ul>

</body>
</html>

Vagoo/entities/templates/entities/theater_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Theaters list</title>
</head>
<body>
    {% if request.user.is_authenticated %}
        <a href="{% url "accounts:logout" %}">خروج کاربر</a>
    {% else %}
        <a href="{% url "accounts:login" %}" }>ورود کاربر</a>
    {% endif %}0
    {% if theaters %}
        <ul>
            {% for theater in theaters %}
                <li>
                    <a href="{% url "entities:theaters_details" pk=theater.id %}">
                    {{ theater.name }}
                    </a>
                </li>
            {% endfor %}
        </ul>
    {% endif %}
    <a href="{% url "entities:theaters_create" %} " target="_blank">اضافه کردن تئاتر جدید</a>
</body>
</html>